### ISSUE TITLE
Make sure python3.7 or greater is added on README.md

### ISSUE THREAD

**Issue by shebistar** [RedHat-EMEA-SSA-Team/hetzner-ocp4#260]
I got this error because I installed python3.6:

`hetzner-ocp4]#` ansible-navigator run -m stdout ./ansible/setup.yml 
Traceback (most recent call last):
  File "/root/.local/bin/ansible-navigator", line 11, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.6/site-packages/ansible_navigator/cli.py", line 102, in main
    new_messages, new_exit_messages = parse_and_update(sys.argv[1:], args=args, initial=True)
  File "/root/.local/lib/python3.6/site-packages/ansible_navigator/initialization.py", line 176, in parse_and_update
    new_messages, new_exit_messages = configurator.configure()
  File "/root/.local/lib/python3.6/site-packages/ansible_navigator/configuration_subsystem/configurator.py", line 106, in configure
    self._post_process()
  File "/root/.local/lib/python3.6/site-packages/ansible_navigator/configuration_subsystem/configurator.py", line 241, in _post_process
    messages, errors = processor(entry=entry, config=self._config)
  File "/root/.local/lib/python3.6/site-packages/ansible_navigator/configuration_subsystem/navigator_post_processor.py", line 32, in wrapper
    messages, exit_messages = func(*args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/ansible_navigator/configuration_subsystem/navigator_post_processor.py", line 505, in mode
    subcommand_action = action_package.get(valid_pkg_name)  # type: ignore
  File "/root/.local/lib/python3.6/site-packages/ansible_navigator/actions/_actions.py", line 56, in get
    _import(package, action)
  File "/root/.local/lib/python3.6/site-packages/ansible_navigator/actions/_actions.py", line 33, in _import
    importlib.import_module(f"{package}.{action}")
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.local/lib/python3.6/site-packages/ansible_navigator/actions/run.py", line 26, in <module>
    from ..runner.api import CommandRunnerAsync
  File "/root/.local/lib/python3.6/site-packages/ansible_navigator/runner/api.py", line 17, in <module>
    from ansible_runner import Runner  # type: ignore
  File "/root/.local/lib/python3.6/site-packages/ansible_runner/__init__.py", line 3, in <module>
    from .interface import run, run_async, \
  File "/root/.local/lib/python3.6/site-packages/ansible_runner/interface.py", line 33, in <module>
    from ansible_runner.streaming import Transmitter, Worker, Processor
  File "/root/.local/lib/python3.6/site-packages/ansible_runner/streaming.py", line 1
    from __future__ import annotations  # allow newer type syntax until 3.10 is our minimum
    ^
SyntaxError: future feature annotations is not defined`

It disappeared after I installed python3.9

**Comment by rbo** [comment]
It looks like a bug/problem with ansible-navigator and not hetzner-ocp4?

**Comment by shebistar** [comment]
Yes, it looks like, because I am trying to use ansible-navigator and it complains about my python 3.6 release. When I upgrade to python 3.9, it complains the playbook about not being able to find the firewalld module when I run the setup.yml playbook.

I will keep searching to see how it goes. Thank you.

**Comment by sshaaf** [comment]
I hit the same thing. seems like an ansible-navigator bug. do we have any workaround?

**Comment by rbo** [comment]
If I remember correctly, switching to RHEL 9 was the solution.

**Comment by sshaaf** [comment]
Also upgrading to Rocky 9 worked for me. 
    3  dnf update
    4  cat /etc/redhat-release
    5  REPO_URL="http://download.rockylinux.org/pub/rocky/9/BaseOS/x86_64/os/Packages/r/"
    6  RELEASE_PKG="rocky-release-9.1-1.11.el9.noarch.rpm"
    7  REPOS_PKG="rocky-repos-9.1-1.11.el9.noarch.rpm"
    8  GPG_KEYS_PKG="rocky-gpg-keys-9.1-1.11.el9.noarch.rpm"
    9  sudo dnf install $REPO_URL/$RELEASE_PKG $REPO_URL/$REPOS_PKG $REPO_URL/$GPG_KEYS_PKG
   10  sudo rm -rf /usr/share/redhat-logos
   11  dnf -y --releasever=9 --allowerasing --setopt=deltarpm=false distro-sync
   12  sudo rpm --rebuilddb
   13  reboot
